# ビルド設定
[build]
  publish = "."
  command = ""  # ビルドコマンドを無効化

# Netlify Functions (バックエンド) の設定
[functions]
  # バックエンドのNode.jsファイルが置かれているディレクトリを指定
  directory = "server/"

# リダイレクト（パスの書き換え）設定
[[redirects]]
  # ブラウザからの `/api/`で始まるリクエストを...
  from = "/api/*"
  # 実際のバックエンド関数のパスに書き換える
  to = "/.netlify/functions/:splat"
  # ステータスコード200は、これが内部的な転送であることを示す
  status = 200

# 開発サーバー設定
[dev]
  # 公開するフォルダを指定します（「.」は現在のディレクトリを意味します）
  publish = "."
  # サーバーが使用するポートをNetlifyが自動で選択するようにします
  port = 8888 # これはNetlify CLIが探す開始点のポートです
